apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: energy-router

images:
  - name: energy-aware-task-router
    newName: energy-aware-task-router
    newTag: latest
